CREATE USER wallmart IDENTIFIED BY wallmart
            ;

GRANT CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE SESSION,
      CREATE SYNONYM,
      CREATE TABLE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE VIEW
  TO wallmart;

ALTER USER wallmart QUOTA UNLIMITED ON USERS;