CREATE USER walmart IDENTIFIED BY walmart;

GRANT CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE SESSION,
      CREATE SYNONYM,
      CREATE TABLE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE VIEW
  TO walmart;

ALTER USER walmart QUOTA UNLIMITED ON USERS;
--drop user walmart CASCADE;