CREATE TABLE CUSTOMER_DIM (
    CustomerID      NUMBER(10),                         -- Unique identifier for the customer
    FirstName       VARCHAR2(50)      NOT NULL,         -- First name of the customer
    LastName        VARCHAR2(50)      NOT NULL,         -- Last name of the customer
    Email           VARCHAR2(100),                      -- Email address of the customer
    Phone           VARCHAR2(15),                       -- Phone number of the customer
    Address         VARCHAR2(255),                      -- Address of the customer
    MembershipDate  DATE              NOT NULL,         -- Date of membership registration
    CONSTRAINT PK_CUSTOMER_DIM PRIMARY KEY (CustomerID) -- Primary key constraint
);
CREATE TABLE DATE_DIM (
    DateID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Year NUMBER(4) NOT NULL,
    Quarter NUMBER(1) CHECK (Quarter BETWEEN 1 AND 4),
    Month NUMBER(2) CHECK (Month BETWEEN 1 AND 12),
    Day NUMBER(2) CHECK (Day BETWEEN 1 AND 31),
    Hour NUMBER(2) CHECK (Hour BETWEEN 0 AND 23),
    Minute NUMBER(2) CHECK (Minute BETWEEN 0 AND 59)
);

CREATE TABLE PRODUCT_DIM (
    ProductID      NUMBER(10)                ,         -- Unique identifier for the PRODUCT
    ProductName    VARCHAR2(50)      NOT NULL,         -- First name of the PRODUCT
    price          NUMBER(10, 2)     NOT NULL,         -- price of the PRODUCT
    CONSTRAINT PK_PRODUCT_DIM PRIMARY KEY (ProductID)  -- Primary key constraint
);
-- Create the Suppliers table
CREATE TABLE SUPPLIERS_DIM (
    SupplierID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SupplierName VARCHAR2(100) NOT NULL,
    ContactName VARCHAR2(50),
    Phone VARCHAR2(15),
    Email VARCHAR2(100),
    Address CLOB
);
CREATE TABLE CATEGORY_DIM (
    CATEGORYID      NUMBER(10)            ,                -- Unique identifier for the CATEGORY
    CATEGORYNAME    VARCHAR2(50)  NOT NULL,                -- Name of the CATEGORY
    DESCRIPTION     CLOB                  ,                -- Description of the CATEGORY
    CONSTRAINT PK_CATEGORYID_DIM PRIMARY KEY (CATEGORYID)  -- Primary key constraint
);


create table Transaction_Fact(
    TransactionID Number NOT NULL,
    ProductID Number NOT NULL,
    DateID Number NOT NULL,
    CustomerID Number NOT NULL,
    CategoryID Number NOT NULL,
    SupplierID Number NOT NULL,
    OrderID Number NOT NULL,
    Quantity Number,
    UnitPrice NUMBER(10, 2) ,
    TotalAmount NUMBER(10, 2),
    CONSTRAINT TransactionID_PK PRIMARY KEY (TransactionID),
    CONSTRAINT ProductID_FK FOREIGN KEY (ProductID) REFERENCES Product_Dim(ProductID),
    CONSTRAINT DateID_FK FOREIGN KEY (DateID) REFERENCES Date_Dim(DateID),
    CONSTRAINT CustomerID_FK FOREIGN KEY (CustomerID) REFERENCES Customer_Dim(CustomerID),
    CONSTRAINT CategoryID_FK FOREIGN KEY (CategoryID) REFERENCES Category_Dim(CategoryID),
    CONSTRAINT SupplierID_FK FOREIGN KEY (SupplierID) REFERENCES Suppliers_Dim(SupplierID)
)